### ISSUE TITLE
AutoComplete single selection acts differently in some scenarios

### ISSUE THREAD

**Issue by jmillar-nanthealth** [feather-design-system/feather-design-system#114]
In some scenarios, I'm seeing that the Autocomplete will auto-select elements, and in other scenarios it will not.
I have been comparing for instance the Feather Single Autocomplete demo (https://feather.nanthealth.com/demos#/Autocomplete-Single) with the equivalent in our internal Nuxt playground.
In the Nuxt demo, if you open the dropdown, it will have an element highlighted, and then when you blur the control, it will auto-select the highlighted element.
In the Feather demo linked above, it does not auto-highlight an element and will therefore not auto-select it.

This is a bug, and I believe the Nuxt behaviour is as designed, but this results in some disparities which we will need to consider - in the Nuxt instance, it is difficult to actually clear the input to be empty and it's non intuitive. In the Feather demo, you simply click clear and unless you specifically select or highlight something, then the element will remain cleared.

**Comment by rikbrowning** [comment]
Is this working as expected?

**Comment by jmillar-nanthealth** [comment]
Seems to be in the latest dev builds. I will re-deploy the demos and verify
