### ISSUE TITLE
NuxtJS 3 Warning

### ISSUE THREAD

**Issue by cdeepal** [feather-design-system/feather-design-system#125]
I am getting this warning when importing featherds modules for the new NuxtJS 3 app we are developing. Any idea what to do about this? (it happens to all feather modules)

WARN @featherds/button doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.

**Comment by jmillar-nanthealth** [comment]
@cdeepal - I believe this has been addressed in the latest release - v0.11.2
Please try it out and let us know if you continue to see issues
