### ISSUE TITLE
Vite Version incompatibility with feather styles

### ISSUE THREAD

**Issue by mrw006** [feather-design-system/feather-design-system#130]
This can potentially be broken into multiple issues:

1.  When trying to integrate feather packages (0.11.2) with vite 3 (using vite-plugin-ssr), I get the following error when trying to load my app:
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for C:\projects\shared\allpayer-plan-updates-portal\node_modules\@featherds\styles\dist\style.css
    at new NodeError (node:internal/errors:372:5)

Relevant packages:
- vite-plugin-ssr 0.4.19
- vite 3.0.3
- @vitejs/plugin-vue 3.0.3
- @featherds/styles 0.11.2

2.  When I use @feather 0.11.2 and vite 2.9.15, I receive the same error as mentioned above:
1:31:18 PM [vite] Error when evaluating SSR module /renderer/PageShell.vue:
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for C:\projects\shared\allpayer-plan-updates-portal\node_modules\@featherds\styles\dist\style.css

Relevant packages:
- vite-plugin-ssr 0.4.19
- vite 2.9.15
- @vitejs/plugin-vue 2.3.4
- @featherds/styles 0.11.2

3.  When I use @feather 0.10.7 and vite 3.0.3 I get a different error:
C:\projects\shared\allpayer-plan-updates-portal\app\node_modules\@featherds\styles\dist\app.js:1
import "./style.css";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)

Relevant packages:
- vite-plugin-ssr 0.4.19
- vite 3.0.3
- @vitejs/plugin-vue 3.0.3
- @featherds/styles 0.10.7

**Comment by rikbrowning** [comment]
What happens if you use the v0.10.7 of @feather and v2 vite? 
It seems that switching to the ecmascript format is not liking us trying to import styles directly. We will have to investigate how to better package these components. Strange that the v0.10 doesn't even work in the newer vite.

I found this https://github.com/vitejs/vite/pull/8454 which I think was released in https://github.com/vitejs/vite/blob/v3.0.8/packages/vite/CHANGELOG.md#305-2022-08-09 Would you mind trying the latest vite?

**Comment by mrw006** [comment]
@feather v0.10.7 and vite v2.9.15 are working.  We can run the app just fine.  Looks like there are some build issues, though.  I'm working through those.

I just tried @feather v0.10.7 and vite 3.0.8.  I am getting the same error mentioned in 3 above.  So nothing has seemed to change yet.

**Comment by rikbrowning** [comment]
@mrw006 could you check adding
```js
ssr:{
    noExternal:[/^@featherds.*/]
  }
```
to you vite.config.js

**Comment by mrw006** [comment]
@rikbrowning, any particular versions of featherds and vite?  I am assuming vite 3....

**Comment by rikbrowning** [comment]
Latest of both, I tried it locally and it seemed to work with that setting.

**Comment by mrw006** [comment]
Looks good to me, I believe we can close this as resolved.  Thanks!
