### ISSUE TITLE
Autocomplete single selection emits an @update:modelValue call twice

### ISSUE THREAD

**Issue by mikewrosey** [feather-design-system/feather-design-system#175]
```
    <FeatherAutocomplete
      label="Items"
      type="single"
      :loading="loading"
      :results="filteredItems"
      @search="search"
      @update:modelValue="setItem"
    ></FeatherAutocomplete>
```

When selecting an option other than the one at the top of the list, `setItem` will be called twice, first with the one at the top of the list, second with the one the user selected.

Looks like you can see it here: https://feather.nanthealth.com/demos#/Autocomplete-Single. If `Users` -> `William` is selected, the input will first flash with `Liam`

Possibly related to https://github.com/feather-design-system/feather-design-system/issues/114

This is not an immediate blocker but does require us to handle the two emits properly.

**Comment by janderson9** [comment]
Closed FEATHER-680
