### ISSUE TITLE
Issue with pagination.

### ISSUE THREAD

**Issue by sdongol-nh** [feather-design-system/feather-design-system#177]
When total record is 0. It gives following calculation error.

![image](https://user-images.githubusercontent.com/128997071/228269314-53fcaee4-279e-4a77-8683-b8226f1cdd2a.png)
 I have to set total to 1 inorder to avoid the Error Calculation Start error.

![image](https://user-images.githubusercontent.com/128997071/228270583-ff7d1dd2-36dc-4901-9c2c-003a93255fc0.png)

Is this some kind of issue or I am setting pagination flags wrong?

**Comment by janderson9** [comment]
"ERROR calculating start" message removed when there are no results.  Also, when there are no results, the page size select list is disabled.
