### ISSUE TITLE
Cannot clear single Autocomplete selection.

### ISSUE THREAD

**Issue by mikewrosey** [feather-design-system/feather-design-system#186]
Please see the video here directly from the autocomplete demo on the feather site.
v.12.20

Looks like when we click outside, it always adds the first item in the list. The only way to clear it is to click the clear button and then click escape after.

[screencast-feather.nanthealth.com-2023.09.25-14_10_01.webm](https://github.com/feather-design-system/feather-design-system/assets/8680122/1ea577ab-3ffa-4eeb-bde8-32e4c855705a)

**Comment by janderson9** [comment]
Autocomplete (type-"single") now defaults to first item in the list only on initial load.  Subsequent expansion of the result list does NOT default to first item.
