### ISSUE TITLE
Typescript Update

### ISSUE THREAD

**Issue by rikbrowning** [feather-design-system/feather-design-system#60]
Update our packages to have better property and event types:

- [x] @featherds/app
- [x] @featherds/app-layout
- [x] @featherds/autocomplete
- [x] @featherds/back-button
- [x] @featherds/badge
- [x] @featherds/button
- [x] @featherds/checkbox
- [x] @featherds/chips
- [x] @featherds/composables
- [x] @featherds/date-input
- [x] @featherds/dialog
- [x] @featherds/drawer
- [x] @featherds/dropdown
- [x] @featherds/expansion
- [x] @featherds/footer
- [x] @featherds/icon
- [x] @featherds/input-helper
- [x] @featherds/input
- [x] @featherds/list
- [x] @featherds/megamenu
- [x] @featherds/menu
- [x] @featherds/navigation-rail
- [x] @featherds/pagination
- [x] @featherds/pdf-viewer
- [x] @featherds/progress
- [x] @featherds/protected
- [x] @featherds/radio
- [x] @featherds/ripple
- [x] @featherds/select
- [x] @featherds/styles
- [x] @featherds/switch
- [x] @featherds/table
- [x] @featherds/tabs
- [x] @featherds/textarea
- [x] @featherds/utils

**Comment by jmillar-nanthealth** [comment]
This has been merged
