### ISSUE TITLE
TS compile errors 'Timeout' is not assignable to type 'number'

### ISSUE THREAD

**Issue by mikewrosey** [feather-design-system/feather-design-system#87]
A couple build errors with `0.10.3`.
`--skipLibCheck` not working in this case as it seems to only apply to .d.ts files. Perhaps there's another workaround but I'm not sure.

```
node_modules/@featherds/ripple/src/components/FeatherRipple.vue:67:11 - error TS2322: Type 'Timeout' is not assignable to type 'number'.

67           this.failsafe = setTimeout(() => {
```
```
node_modules/@featherds/select/src/components/FeatherSelect.vue:315:7 - error TS2322: Type 'Timeout' is not assignable to type 'number'.

315       this.delayTimeout = setTimeout(() => {
```

**Comment by rikbrowning** [comment]
Hey @mikewrosey what do you have as your lib property in your tsconfig?

**Comment by mikewrosey** [comment]
> Hey @mikewrosey what do you have as your lib property in your tsconfig?

    "lib": ["esnext", "dom"],

**Comment by rikbrowning** [comment]
You got a link to the full config?

**Comment by jmillar-nanthealth** [comment]
@mikewrosey - looking into this at the moment. We're updating the usages so they shouldn't throw these errors in future.
Will update once we have the fix in place.

**Comment by rikbrowning** [comment]
The main issue comes from having @types/node installed as a dependency, it imports the wrong type information for setTimeout as it should be a number. We have tried our best to mitigate this issue with the release of  v0.10.6 Let us know if there are any more issues.

**Comment by mikewrosey** [comment]
@rikbrowning @jmillar-nanthealth Thanks for the quick fix guys and great job on all this! Nice to have better type safety.
